doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Veliu\RateManu\Infra\Doctrine\Migrations': '%kernel.project_dir%/src/Infra/Doctrine/Migrations'
    enable_profiler: false
