rest_authentication:
  resource:
    path: ../src/Application/RestApi/Authentication/
    namespace: Veliu\RateManu\Application\RestApi\Authentication
  type: attribute
  prefix: /api/authentication/

rest_user:
  resource:
    path: ../src/Application/RestApi/User/
    namespace: Veliu\RateManu\Application\RestApi\User
  type: attribute
  prefix: /api/user/

rest_food:
  resource:
    path: ../src/Application/RestApi/Food/
    namespace: Veliu\RateManu\Application\RestApi\Food
  type: attribute
  prefix: /api/food/

rest_food-rating:
  resource:
    path: ../src/Application/RestApi/Rating/
    namespace: Veliu\RateManu\Application\RestApi\Rating
  type: attribute
  prefix: /api/food-rating/

rest_ingredient:
  resource:
    path: ../src/Application/RestApi/Ingredient/
    namespace: Veliu\RateManu\Application\RestApi\Ingredient
  type: attribute
  prefix: /api/ingredient/

api_token_invalidate:
  path: /api/token/invalidate