rest_authentication:
  resource:
    path: ../src/Application/RestApi/Authentication/
    namespace: Veliu\RateManu\Application\RestApi\Authentication
  type: attribute
  prefix: /api/authentication/
