parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\RateManu\Infra\Doctrine\Repository\:
        resource: '../src/Infra/Doctrine/Repository'

    Veliu\RateManu\Infra\Symfony\EventListener\:
        resource: '../src/Infra/Symfony/EventListener'

    Veliu\RateManu\Domain\User\Handler\:
        resource: '../src/Domain/User/Handler'

    Veliu\RateManu\Domain\Notification\Handler\:
        resource: '../src/Domain/Notification/Handler'

    Veliu\RateManu\Domain\Food\Handler\:
        resource: '../src/Domain/Food/Handler'

    Veliu\RateManu\Domain\Rating\Handler\:
        resource: '../src/Domain/Rating/Handler'

    # Controller
    Veliu\RateManu\Application\RestApi\Authentication\:
        resource: '../src/Application/RestApi/Authentication'
        tags: ['controller.service_arguments']

    Veliu\RateManu\Application\RestApi\User\:
        resource: '../src/Application/RestApi/User'
        tags: [ 'controller.service_arguments' ]

    Veliu\RateManu\Application\RestApi\Food\:
        resource: '../src/Application/RestApi/Food'
        tags: [ 'controller.service_arguments' ]

    Veliu\RateManu\Application\RestApi\Rating\:
        resource: '../src/Application/RestApi/Rating'
        tags: [ 'controller.service_arguments' ]


    Veliu\RateManu\Application\ValueResolver\:
        resource: '../src/Application/ValueResolver'
        tags: [ 'controller.argument_value_resolver', 'controller.targeted_value_resolver' ]

    Veliu\RateManu\Domain\User\UserRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\UserRepository'
    Veliu\RateManu\Domain\Group\GroupRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\GroupRepository'
    Veliu\RateManu\Domain\Food\FoodRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\FoodRepository'
    Veliu\RateManu\Domain\Rating\RatingRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\RatingRepository'

    Veliu\RateManu\Application\RestApi\UserChecker: ~