parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\RateManu\Infra\Doctrine\Repository\:
        resource: '../src/Infra/Doctrine/Repository'

    Veliu\RateManu\Domain\UserRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\UserRepository'