parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\RateManu\Infra\Doctrine\Repository\:
        resource: '../src/Infra/Doctrine/Repository'

    Veliu\RateManu\Infra\Symfony\EventListener\:
        resource: '../src/Infra/Symfony/EventListener'

    Veliu\RateManu\Domain\User\Handler\:
        resource: '../src/Domain/User/Handler'

    Veliu\RateManu\Domain\Notification\Handler\:
        resource: '../src/Domain/Notification/Handler'

    # Controller
    Veliu\RateManu\Application\RestApi\Authentication\:
        resource: '../src/Application/RestApi/Authentication'
        tags: ['controller.service_arguments']

    Veliu\RateManu\Application\RestApi\User\:
        resource: '../src/Application/RestApi/User'
        tags: [ 'controller.service_arguments' ]


    Veliu\RateManu\Application\ValueResolver\:
        resource: '../src/Application/ValueResolver'
        tags: [ 'controller.argument_value_resolver', 'controller.targeted_value_resolver' ]

    Veliu\RateManu\Domain\UserRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\UserRepository'

    Veliu\RateManu\Application\RestApi\UserChecker: ~