parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Veliu\RateManu\Infra\Doctrine\Repository\:
        resource: '../src/Infra/Doctrine/Repository'

    Veliu\RateManu\Infra\Symfony\EventListener\:
        resource: '../src/Infra/Symfony/EventListener'

    Veliu\RateManu\Domain\User\Handler\:
        resource: '../src/Domain/User/Handler'

    Veliu\RateManu\Domain\Notification\Handler\:
        resource: '../src/Domain/Notification/Handler'

    # Controller
    Veliu\RateManu\Application\RestApi\Authentication\RegisterUserAction:
        tags: ['controller.service_arguments']

    Veliu\RateManu\Application\RestApi\Authentication\ConfirmUserRegistrationAction:
        tags: [ 'controller.service_arguments' ]

    Veliu\RateManu\Domain\UserRepositoryInterface: '@Veliu\RateManu\Infra\Doctrine\Repository\UserRepository'

    Veliu\RateManu\Application\RestApi\UserChecker: ~